[http.middlewares.simpleAuth.basicAuth]
  users = [
    "admin:$apr1$futE7qd5$CWn820MIlYZm4RILGBlB0/"
  ]

[http.routers.api]
  rule = "Host(`monitor.localhost`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"