[http.middlewares.simpleAuth.basicAuth]
  users = [
    "ADD YOUR SECRET HERE"
  ]

[http.routers.api]
  rule = "Host(`monitor.your-domain.com`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"